import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import yaml from 'js-yaml';
import { JavaProject, type SourceFile } from './java/model.js';

export interface DetectedConfig {
  yaml: string;
  notes: string[];
}

/**
 * Proposes an aeris.config.yaml from the sources: context holders (static
 * methods returning the session from the Reactor Context), the
 * Authentication class, an idempotency web filter and active profiles.
 */
export async function detectConfig(rootDir: string, files: readonly SourceFile[]): Promise<DetectedConfig> {
  const project = await JavaProject.load(files);
  const notes: string[] = [];
  const sources: { method: string; kind: string; type: string }[] = [];
  for (const type of project.types.values()) {
    for (const method of type.methods) {
      if (!method.modifiers.has('static') || method.params.length !== 0 || method.body === undefined) continue;
      if (!/deferContextual|ReactiveSecurityContextHolder/.test(method.body.text)) continue;
      if (method.returnType.name !== 'reactor.core.publisher.Mono') continue;
      const payload = method.returnType.args[0];
      if (payload === undefined) continue;
      const optional = payload.name === 'java.util.Optional';
      const record = project.type(optional ? payload.args[0]?.name ?? '' : payload.name);
      if (record === undefined || (record.kind !== 'record' && record.kind !== 'class')) continue;
      // A session carries identities (tenant, organization, user...), not request metadata.
      const components = record.kind === 'record' ? record.recordComponents : record.fields;
      if (!components.some((component) => component.type.name === 'java.util.UUID' && /tenant|organi[sz]ation|user|actor|account/i.test(component.name))) continue;
      sources.push({ method: `${type.simple}.${method.name}`, kind: optional ? 'optional' : 'required', type: record.fqn });
    }
  }
  if (sources.length === 0) notes.push('No context holder found: declare context.sources for the session claims (tenant, organization, user).');
  const authentication = [...project.types.values()].find((type) =>
    type.kind === 'class' && type.superclass !== undefined && /AbstractAuthenticationToken$/.test(type.superclass.name));
  const idempotencyFilter = files.find((file) => /implements\s+WebFilter/.test(file.content) && /Idempotency-Key/.test(file.content));
  if (idempotencyFilter !== undefined) notes.push(`Idempotency filter detected in ${idempotencyFilter.path}: check the covered methods and paths.`);
  else notes.push('No Idempotency-Key filter found: creations (POST) will stay online-only until the backend deduplicates replays.');
  let profiles: string[] = [];
  for (const candidate of ['src/main/resources/application.yml', 'src/main/resources/application.yaml']) {
    const found = files.find((file) => file.path.endsWith('Application.java'));
    const base = found === undefined ? rootDir : join(rootDir, found.path.split('/src/main/')[0] ?? '');
    try {
      const document = yaml.load(await readFile(join(base, candidate), 'utf8')) as { spring?: { profiles?: { active?: string } } } | undefined;
      const active = document?.spring?.profiles?.active;
      if (typeof active === 'string') profiles = active.split(',').map((profile) => profile.trim()).filter((profile) => !profile.startsWith('${'));
    } catch {
      // No configuration file at this location.
    }
  }
  const config = {
    activeProfiles: profiles,
    serverTimeZone: 'UTC',
    context: {
      sources,
      ...(authentication === undefined ? {} : { authentication: authentication.fqn }),
    },
    ...(idempotencyFilter === undefined ? {} : { idempotency: { header: 'Idempotency-Key', methods: ['POST', 'PUT', 'PATCH', 'DELETE'], paths: ['/api/**'] } }),
    scopeClaims: { tenantId: ['tenantId'], organizationId: ['organizationId'] },
    publicEntities: [],
    onlineOnly: [],
  };
  const header = [
    '# AERIS Behavior Compiler configuration (generated by `aeris init`, review before use).',
    '# activeProfiles: Spring profiles of the production deployment (selects @Profile beans).',
    '# context.sources: static methods returning the verified session; their record components are the session claims.',
    '# idempotency: only declare it if the backend really deduplicates replays carrying this header.',
    '# scopeClaims: which entity properties restrict rows to a session claim (projections never leave this scope).',
    '# publicEntities: reference data every session may hold. onlineOnly: endpoint globs that must never run offline.',
    '',
  ].join('\n');
  return { yaml: header + yaml.dump(config, { lineWidth: 120 }), notes };
}
