import type { JsonValue } from '../ir/types.js';
import type { Captured, Effect } from './executor.js';
import { isUuid } from './values.js';
import type { OutboxRecord, StoredRow } from './store/LocalStore.js';
import type { WireError } from '../protocol.js';

/** Operation life cycle (architecture document, section 9.1). */
export type OperationState =
  | 'QUEUED'
  | 'SYNCING'
  | 'SERVER_COMMITTED'
  | 'CONFLICT'
  | 'REJECTED';

export const PENDING_STATES: ReadonlySet<OperationState> = new Set(['QUEUED', 'SYNCING']);
export const FAILED_STATES: ReadonlySet<OperationState> = new Set(['CONFLICT', 'REJECTED']);

export interface OutboxEntry {
  operationId: string;
  sequence: number;
  state: OperationState;
  endpointId: string;
  method: string;
  /** Concrete request path (rewritten when local ids are remapped). */
  path: string;
  params: Record<string, string>;
  query: Record<string, string>;
  body: JsonValue | null;
  /** Trusted claims the program read, frozen for deterministic re-execution. */
  context: Record<string, JsonValue>;
  captured: { now: number; uuids: string[] };
  /** Identifiers generated by this operation, i.e. its uuid slots. */
  localIds: string[];
  dependencies: string[];
  artifactVersion: number;
  projectionVersion: string;
  baseCursor: string | null;
  preconditionHash: string;
  /** Undo log: applied local effects with before images, in application order. */
  effects: Effect[];
  localResponse: { status: number; body: JsonValue | null };
  /** Binds the operation to the session that created it. */
  subject: string;
  createdAt: number;
  attempts: number;
  nextAttemptAt: number;
  serverCursor?: string;
  canonicalResponse?: { status: number; body: JsonValue | null };
  error?: WireError;
  updatedAt: number;
}

export function toRecord(entry: OutboxEntry): OutboxRecord {
  return entry as unknown as OutboxRecord;
}

export function fromRecord(record: OutboxRecord): OutboxEntry {
  return record as unknown as OutboxEntry;
}

/** Every string leaf of a JSON value. */
export function collectStrings(value: JsonValue | undefined, out: Set<string> = new Set()): Set<string> {
  if (typeof value === 'string') out.add(value.toLowerCase());
  else if (Array.isArray(value)) for (const item of value) collectStrings(item, out);
  else if (value !== null && typeof value === 'object') for (const item of Object.values(value)) collectStrings(item, out);
  return out;
}

/**
 * Operations this request depends on: pending operations whose local ids
 * appear in the request, or which touched the same rows.
 */
export function findDependencies(
  pending: readonly OutboxEntry[],
  request: { params: Record<string, string>; query: Record<string, string>; body: JsonValue | null },
  effects: readonly Effect[],
): string[] {
  const referenced = collectStrings(request.body);
  for (const value of [...Object.values(request.params), ...Object.values(request.query)]) referenced.add(value.toLowerCase());
  const touched = new Set(effects.map((effect) => rowId(effect.entity, effect.key)));
  const dependencies: string[] = [];
  for (const entry of pending) {
    const byId = entry.localIds.some((id) => referenced.has(id.toLowerCase()));
    const byRow = entry.effects.some((effect) => touched.has(rowId(effect.entity, effect.key)));
    if (byId || byRow) dependencies.push(entry.operationId);
  }
  return dependencies;
}

export function rowId(entity: string, key: JsonValue): string {
  return `${entity}\u0000${typeof key === 'string' ? key.toLowerCase() : JSON.stringify(key)}`;
}

/** Replaces every occurrence of a local id by its server id, deep. */
export function remapValue<T extends JsonValue | undefined>(value: T, idMap: ReadonlyMap<string, string>): T {
  if (idMap.size === 0) return value;
  if (typeof value === 'string') {
    if (!isUuid(value)) return value;
    return (idMap.get(value.toLowerCase()) ?? value) as T;
  }
  if (Array.isArray(value)) return value.map((item) => remapValue(item, idMap)) as unknown as T;
  if (value !== null && typeof value === 'object') {
    const out: Record<string, JsonValue> = {};
    for (const [key, item] of Object.entries(value)) out[key] = remapValue(item as JsonValue, idMap);
    return out as T;
  }
  return value;
}

export function remapPath(path: string, idMap: ReadonlyMap<string, string>): string {
  if (idMap.size === 0) return path;
  return path.split('/').map((segment) => {
    let decoded: string;
    try {
      decoded = decodeURIComponent(segment);
    } catch {
      return segment;
    }
    const mapped = isUuid(decoded) ? idMap.get(decoded.toLowerCase()) : undefined;
    return mapped === undefined ? segment : encodeURIComponent(mapped);
  }).join('/');
}

export function remapRow(row: StoredRow | null, idMap: ReadonlyMap<string, string>): StoredRow | null {
  return row === null ? null : remapValue(row, idMap);
}

export function remapEntry(entry: OutboxEntry, idMap: ReadonlyMap<string, string>): OutboxEntry {
  if (idMap.size === 0) return entry;
  const params: Record<string, string> = {};
  for (const [name, value] of Object.entries(entry.params)) params[name] = remapValue(value, idMap);
  const query: Record<string, string> = {};
  for (const [name, value] of Object.entries(entry.query)) query[name] = remapValue(value, idMap);
  return {
    ...entry,
    path: remapPath(entry.path, idMap),
    params,
    query,
    body: remapValue(entry.body, idMap),
    effects: entry.effects.map((effect) => ({
      ...effect,
      key: remapValue(effect.key, idMap),
      before: remapRow(effect.before, idMap),
      after: remapRow(effect.after, idMap),
    })),
    localResponse: { ...entry.localResponse, body: remapValue(entry.localResponse.body, idMap) },
  };
}

export function capturedOf(entry: OutboxEntry): Captured {
  return { now: entry.captured.now, uuids: entry.captured.uuids };
}

/** Exponential backoff with full jitter, capped. */
export function backoff(attempts: number, random: () => number, baseMs = 1_000, capMs = 5 * 60_000): number {
  const ceiling = Math.min(capMs, baseMs * 2 ** Math.min(attempts, 20));
  return Math.floor(ceiling / 2 + random() * ceiling / 2);
}
