// Compatibility stub after the matching system was removed. Handler
// templates are no longer generated by this project. This stub satisfies
// the imports of ScaffoldCommand and MappingGenerator.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

export const HANDLERS_FILE = 'offline-handlers.stub.ts';

/** Writes an empty handlers template. */
export function writeHandlerStub(
  _drafts: import('./types.js').OperationDraft[],
  generatedAt: string,
  path: string,
): void {
  const content = `/* eslint-disable */
/**
 * GENERATED by "offline-sync discover" on ${generatedAt}.
 *
 * This file is empty: handler generation is no longer necessary.
 * Interception is now configured in offline-sync.entites.yaml.
 */
export const handlers = {} as const;
`;
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, 'utf8');
}
