import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, join } from 'node:path';

import { QUEUE_COLUMNS, QUEUE_TABLE } from '../core/PendingQueue.js';
import { DEAD_LETTER_COLUMNS, DEAD_LETTER_TABLE_NAME } from '../core/DeadLetterStore.js';

export type SqliteType = 'text' | 'integer' | 'real';

export interface ReplicatedColumn {
  name: string;
  type: SqliteType;
}

/** A replicated table, as a sync bucket defines it. `buckets` lists every bucket that replicates it. */
export interface ReplicatedTable {
  name: string;
  columns: ReplicatedColumn[];
  buckets: string[];
}

/** A local-only table found in the schema file, kept verbatim across regenerations. */
export interface LocalTable {
  name: string;
  columns: ReplicatedColumn[];
}

export interface ReplicatedSchema {
  /** The queried URL, or the re-read file. */
  source: string;
  tables: ReplicatedTable[];
  /** Hand-added local tables (queue and dead-letter store excluded), found by reading the file. */
  localTables?: LocalTable[];
  /** `library`: the engine's own rules-parsing library. `local-reader`: the fallback. */
  analyzedBy?: 'library' | 'local-reader';
}

export const SCHEMA_FILE = 'src/services/offline/schema.ts';

export class SchemaError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'SchemaError';
  }
}

/**
 * Keeps only the tables of the declared buckets. An empty list means "all",
 * same convention as ScopeFilter's `pathPrefixes`. Patterns accept a
 * trailing star: `yownews_*` matches `yownews_tenant` and `yownews_org`.
 */
export function filterByBuckets(
  schema: ReplicatedSchema,
  patterns: readonly string[],
): ReplicatedSchema {
  if (patterns.length === 0) return schema;

  const kept = (bucket: string): boolean =>
    patterns.some((p) =>
      p.endsWith('*') ? bucket.startsWith(p.slice(0, -1)) : bucket === p,
    );

  const tables = schema.tables
    .filter((t) => t.buckets.some(kept))
    .map((t) => ({ ...t, buckets: t.buckets.filter(kept) }));

  return {
    source: schema.source,
    tables,
    ...(schema.localTables !== undefined ? { localTables: schema.localTables } : {}),
    ...(schema.analyzedBy !== undefined ? { analyzedBy: schema.analyzedBy } : {}),
  };
}

/** Rewrites the application's schema file in full. Nothing here is meant to be edited by hand. */
export function writeSchemaFile(
  schema: ReplicatedSchema,
  generatedAt: string,
  path: string,
): void {
  const tables = [...schema.tables].sort((a, b) => a.name.localeCompare(b.name));

  const body = tables.map((table) => {
    const columns = table.columns
      .filter((c) => c.name !== 'id')
      .map((c) => `        ${c.name}: column.${c.type},`)
      .join('\n');

    return [
      `    // bucket(s): ${table.buckets.join(', ')}`,
      `    ${table.name}: new Table(`,
      '      {',
      columns,
      '      },',
      '      { trackMetadata: true },',
      '    ),',
    ].join('\n');
  });

  const queueBlock = [
    `    ${QUEUE_TABLE}: new Table(`,
    '      {',
    QUEUE_COLUMNS.map((c) => `        ${c}: column.text,`).join('\n'),
    '      },',
    '      { localOnly: true },',
    '    ),',
  ].join('\n');

  const deadLetterBlock = [
    `    ${DEAD_LETTER_TABLE_NAME}: new Table(`,
    '      {',
    Object.entries(DEAD_LETTER_COLUMNS)
      .map(([name, type]) => `        ${name}: column.${type},`)
      .join('\n'),
    '      },',
    '      { localOnly: true },',
    '    ),',
  ].join('\n');

  // Any other local table found while reading is re-emitted verbatim, under
  // whatever name it has: it's how a hand-added table survives regeneration.
  const otherLocalBlocks = (schema.localTables ?? [])
    .filter((t) => t.name !== QUEUE_TABLE && t.name !== DEAD_LETTER_TABLE_NAME)
    .map((table) =>
      [
        `    ${table.name}: new Table(`,
        '      {',
        table.columns.map((c) => `        ${c.name}: column.${c.type},`).join('\n'),
        '      },',
        '      { localOnly: true },',
        '    ),',
      ].join('\n'),
    );

  const header = `/* eslint-disable */
/**
 * GENERATED by "offline-sync schema" on ${generatedAt}.
 * Source: ${schema.source}
 *
 * DO NOT EDIT: this file is rewritten in full on every run. Table names,
 * columns and types come from the sync engine, via the sync rules and the
 * replicated database.
 *
 * ${tables.length} table(s) declared. A replicated table ABSENT from this
 * file is stored without being queryable, silently.
 *
 * "id" is never declared: the engine adds it to every table itself.
 */
import { column, Schema, Table } from '@powersync/web';

export const AppSchema = new Schema({
`;

  const footer = `});

export type Database = (typeof AppSchema)['types'];
`;

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(
    path,
    header +
      body.join('\n') +
      '\n' +
      queueBlock +
      '\n' +
      deadLetterBlock +
      '\n' +
      (otherLocalBlocks.length > 0 ? otherLocalBlocks.join('\n') + '\n' : '') +
      footer,
    'utf8',
  );
}

/**
 * Re-reads a schema file written earlier. Strict and literal on purpose: the
 * file was written by `writeSchemaFile`, its shape is known exactly. A file
 * that doesn't match it is reported rather than guessed at.
 */
export function readSchemaFile(cwd: string, path: string): ReplicatedSchema | undefined {
  const fullPath = isAbsolute(path) ? path : join(cwd, path);
  if (!existsSync(fullPath)) return undefined;

  const text = readFileSync(fullPath, 'utf8');
  const source = /^ \* Source: (.+)$/m.exec(text)?.[1]?.trim() ?? fullPath;

  const tables: ReplicatedTable[] = [];
  const localTables: LocalTable[] = [];
  const lines = text.split('\n');
  let buckets: string[] = [];
  let current: { name: string; columns: ReplicatedColumn[] } | undefined;

  for (const line of lines) {
    const bucketComment = /^\s*\/\/ bucket\(s\): (.*)$/.exec(line);
    if (bucketComment !== null) {
      buckets = (bucketComment[1] ?? '')
        .split(',')
        .map((s) => s.trim())
        .filter((s) => s.length > 0);
      continue;
    }

    const start = /^\s*([A-Za-z_][A-Za-z0-9_]*): new Table\($/.exec(line);
    if (start !== null) {
      current = { name: start[1]!, columns: [] };
      continue;
    }

    const column = /^\s*([A-Za-z_][A-Za-z0-9_]*): column\.(text|integer|real),$/.exec(line);
    if (column !== null && current !== undefined) {
      current.columns.push({ name: column[1]!, type: column[2] as SqliteType });
      continue;
    }

    const options = /^\s*\{\s*(localOnly|trackMetadata):\s*true\s*\},$/.exec(line);
    if (options !== null && current !== undefined) {
      if (options[1] === 'localOnly') {
        localTables.push({ name: current.name, columns: current.columns });
      } else {
        tables.push({ name: current.name, columns: current.columns, buckets });
      }
      current = undefined;
      buckets = [];
    }
  }

  if (tables.length === 0) {
    throw new SchemaError(
      `${path} exists but no table was recognized in it. This file is ` +
        'generated by "offline-sync schema": regenerate it rather than fixing it by hand.',
    );
  }

  return {
    source,
    tables,
    ...(localTables.length > 0 ? { localTables } : {}),
  };
}
