import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { loadConfig } from './ConfigLoader.js';
import { SCHEMA_FILE } from './ReplicatedSchema.js';
import type { SyncConfig } from './types.js';

export const TOKENS_FILE = 'tokens.ts';
export const INIT_FILE = 'init.ts';

export const DEFAULT_TOKEN_ENDPOINT = '/api/auth/powersync-token';

export interface ScaffoldOptions {
  cwd: string;
  loadConfigFn?: (cwd: string) => SyncConfig;
}

export interface WrittenFile {
  path: string;
  written: boolean;
  reason?: string;
}

export interface ScaffoldResult {
  files: WrittenFile[];
  /** Directory everything was dropped into. */
  dir: string;
}

export function scaffold(options: ScaffoldOptions): ScaffoldResult {
  const cwd = options.cwd;
  const config = (options.loadConfigFn ?? loadConfig)(cwd);

  const dir = dirname(config.powersync?.schemaFile ?? SCHEMA_FILE);
  const endpoint = config.powersync?.tokenEndpoint ?? DEFAULT_TOKEN_ENDPOINT;

  mkdirSync(join(cwd, dir), { recursive: true });

  return {
    dir,
    files: [
      drop(cwd, join(dir, TOKENS_FILE), tokensTemplate(endpoint)),
      drop(cwd, join(dir, INIT_FILE), initTemplate()),
    ],
  };
}

/** Writes a file, unless it exists: it may hold work done by hand. */
function drop(cwd: string, path: string, content: string): WrittenFile {
  const fullPath = join(cwd, path);
  if (existsSync(fullPath)) {
    return { path, written: false, reason: 'already exists -- nothing was touched' };
  }
  writeFileSync(fullPath, content, 'utf8');
  return { path, written: true };
}

function tokensTemplate(endpoint: string): string {
  return `/**
 * Where this application gets its tokens from.
 *
 * GENERATED once by "offline-sync scaffold", then TO BE FILLED IN: it's the
 * only file in the wiring that knows the project's authentication. Never
 * rewritten.
 *
 * TWO TOKENS, AND THEY DON'T COINCIDE:
 *   - the CHANNEL token authorizes only one thing, opening the sync stream.
 *     Short, minted by a dedicated endpoint, meant for the engine;
 *   - the APPLICATIVE token is the ordinary session, sent to the business
 *     server.
 *
 * Confusing them works until the day one expires before the other.
 */
import type { TokenProvider } from '@ksm/offline-sync';

const CHANNEL_ENDPOINT = '${endpoint}';

export class ApplicationTokens implements TokenProvider {
  /**
   * RETURNING null AND THROWING DON'T MEAN THE SAME THING:
   *   - null  -> the user isn't signed in. The engine opens no channel, and
   *              doesn't retry. A valid answer;
   *   - throw -> a failure. The engine will retry.
   * Returning null on a failure would make a network outage look like a
   * sign-out, and sync would never resume on its own.
   */
  async getStreamToken(): Promise<string | null> {
    const response = await fetch(CHANNEL_ENDPOINT, {
      method: 'POST',
      credentials: 'include',
      // TO FILL IN if your server requires other headers.
    });

    if (response.status === 401 || response.status === 403) return null;
    if (!response.ok) {
      throw new Error(\`channel token refused (\${response.status})\`);
    }

    const body: unknown = await response.json();
    // TO CHECK: your server's response envelope. Here { data: { token } }.
    return (body as { data?: { token?: string } })?.data?.token ?? null;
  }

  /** The channel token is short-lived; asking for a new one is simpler than refreshing it. */
  async refreshStreamToken(): Promise<string | null> {
    return this.getStreamToken();
  }

  /** Sent to the business server in the Authorization header. */
  async getApplicativeToken(): Promise<string | null> {
    // TO FILL IN: wherever your application keeps the user's session.
    return null;
  }

  async refreshApplicativeToken(): Promise<string | null> {
    // TO FILL IN: your session renewal mechanism.
    return this.getApplicativeToken();
  }
}
`;
}

/** The order is imposed, not a preference: nothing to decide here, but plenty to get wrong. */
function initTemplate(): string {
  return `/**
 * Module wiring. GENERATED by "offline-sync scaffold".
 *
 * There's NOTHING to decide here -- which is why it can be generated. What
 * belongs to your application lives in tokens.ts, next to this file.
 *
 * THE ORDER OF THE SIX CONSTRUCTIONS IS IMPOSED, and a mistake doesn't show
 * right away: a module wired in the wrong order starts, then misbehaves
 * later. That's this file's reason to exist.
 *
 * REGENERATE when the module changes version. Since tokens.ts is never
 * touched, that costs nothing.
 */
'use client';

import { PowerSyncDatabase } from '@powersync/web';
import {
  ConsoleLogger,
  DeadLetterStore,
  ErrorHandlerRegistry,
  FetchClient,
  OfflineSync,
  OfflineSyncConnector,
} from '@ksm/offline-sync';
import {
  PowerSyncConnector,
  PowerSyncLocalDatabase,
  tableColumnsFromSchema,
} from '@ksm/offline-sync/powersync';

import { entities } from './entities';
import { AppSchema } from './schema';
import { ApplicationTokens } from './tokens';

const DATABASE_FILE = 'offline-sync.db';

/** Called ONCE, at startup. This is exactly what the app's React provider imports. */
export async function initSync(): Promise<OfflineSync> {
  const engineUrl = process.env.NEXT_PUBLIC_POWERSYNC_URL;
  if (engineUrl === undefined || engineUrl.length === 0) {
    throw new Error(
      'NEXT_PUBLIC_POWERSYNC_URL is empty: the browser has nowhere to reach ' +
        'the sync engine.',
    );
  }

  // 1. The engine. The application builds it, NEVER the module.
  const engine = new PowerSyncDatabase({
    schema: AppSchema,
    database: { dbFilename: DATABASE_FILE },
  });

  // 2. The local database, seen through the module's port.
  const db = new PowerSyncLocalDatabase(engine);

  const logger = new ConsoleLogger();

  // 3. What happens to definitively rejected writes.
  const deadLetters = new DeadLetterStore({ db });
  const errors = new ErrorHandlerRegistry({ logger });

  // 4. Deferred-upload logic, neutral with respect to the engine.
  const connector = new OfflineSyncConnector({
    http: new FetchClient({}),
    tokens: new ApplicationTokens(),
    deadLetters,
    errors,
    logger,
    syncEndpoint: engineUrl,
    db,
    onReauthRequired: () => {
      logger.error(
        'session expired: pending writes are kept, sign in again for them to go out',
      );
    },
    // Called each time a write is definitively rejected (not a network
    // hiccup: the server said no). Push the news to your own UI here, or to
    // the display-only element from "@ksm/offline-sync/ui".
    onDeadLetter: (entry) => {
      logger.error('write rejected, kept in the dead-letter store', {
        operationId: entry.operationId,
        reason: entry.reason,
      });
    },
  });

  // 5. The bridge: the only object that knows the shape of the engine's writes.
  const bridge = new PowerSyncConnector({ db: engine, connector });

  // 6. The module. It asks the bridge for the database -- the application
  //    never gives it directly.
  //
  //    "entities" says which table for which requests; "tableColumns" says
  //    what columns those tables really carry. With both, the module
  //    composes its own SQL at request time -- no handlers to write, no
  //    operations map to keep in sync.
  const sync = await OfflineSync.create({
    connector: bridge,
    entities,
    tableColumns: tableColumnsFromSchema(AppSchema),
    logger,
  });

  // The channel opens LAST: any earlier, a downstream update would reach a
  // module not yet ready to route it.
  await engine.connect(bridge);

  return sync;
}
`;
}
